Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false


Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  Enabled: true
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line
Naming/PredicateMethod:
  Enabled: false

# Special overrides for mrt-zk
Naming/MethodParameterName:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Naming/AccessorMethodName: 
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false