version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo

phases:
  pre_build:
    commands:
      - export AWS_ACCOUNT_ID=`aws sts get-caller-identity| jq -r .Account`
      - echo $AWS_ACCOUNT_ID
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain cdlib-uc3-mrt --domain-owner $AWS_ACCOUNT_ID --region us-west-2 --query authorizationToken --output text`
      - cat ~/.m2/settings.xml
      - force-failure
      - echo s3://${S3CFBUCKET}/api 
      - aws s3 ls s3://${S3CFBUCKET}/
      - git clone https://github.com/CDLUC3/mrt-core2.git
      - mvn -ntp install -f mrt-core2/pom.xml -Pparent
      - mvn -ntp install -f mrt-core2/reflect/pom.xml

  build:
    commands:
      - mvn -ntp clean install -Ddocker.skip -DskipITs -Dmaven.test.skip=true
      - mvn -ntp javadoc:javadoc
      - cd src/main/ruby
      - bundle install
      - bundle exec rdoc lib/*.rb
      - cd ../../..
      - rm -rf api
      - mkdir -p api/java api/ruby
      - cp -r target/site/apidocs/* api/java
      - cp -r src/main/ruby/doc/* api/ruby
      - echo aws s3 cp --recursive api s3://${S3CFBUCKET}/api 
      - aws s3 cp --recursive api s3://${S3CFBUCKET}/api
  post_build:
    commands:
      #- aws s3 rm s3://${S3CFBUCKET}/api --recursive
