version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo

phases:
  pre_build:
    commands:
      - git clone https://github.com/CDLUC3/mrt-core2.git
      - cd mrt-core2 
      - mvn clean install -f dep_core/mrt-core2/pom.xml -Pparent
  build:
    commands:
      - mvn install -Ddocker.skip -DskipITs -Dmaven.test.skip=true
      - mvn clean javadoc:javadoc
      - cd src/main/ruby
      - bundle install
      - bundle exec rdoc lib/*.rb
  post_build:
    commands:
      - echo Goodbye