version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo

phases:
  pre_build:
    commands:
      - echo s3://${S3CFBUCKET}/api 
      - aws s3 ls s3://${S3CFBUCKET}/
      - pwd
      - git clone https://github.com/CDLUC3/merritt-docker.git
      - cd merritt-docker/mrt-services/dep_core
      - git clone https://github.com/CDLUC3/mrt-core2.git
      - mvn -ntp install -f mrt-core2/pom.xml -Pparent
      - cd ../dep_zk
      - git clone https://github.com/CDLUC3/mrt-zk.git
      - cd mrt-zk
      - pwd

  build:
    commands:
      - mvn -ntp install -Ddocker.skip -DskipITs -Dmaven.test.skip=true
      - mvn -ntp javadoc:javadoc
      - cd src/main/ruby
      - bundle install
      - bundle exec rdoc lib/*.rb
      - cd ../../..
      - rm -rf api
      - mkdir -p api/java api/ruby
      - cp -r target/site/apidocs/* api/java
      - cp -r src/main/ruby/doc/* api/ruby
  post_build:
    commands:
      #- aws s3 rm s3://${S3CFBUCKET}/api --recursive
      echo aws s3 cp --recursive api s3://${S3CFBUCKET}/api 
      aws s3 cp --recursive api s3://${S3CFBUCKET}/api